### PR TITLE
Created AddGroupCommand and AddHouseCommand

### LINKED ISSUE #25: Add new group command

### LINKED ISSUE #26: Add new house command

### PR DESCRIPTION
**Pull request by shanseet**
Not complete; requires slight model restructuring
fixes #25 and fixes #26

### CODE REVIEW

**Comment by weizhang05** [comment]
Noticed the model and storage component has some form of implementation done, in this case it is better to be under a separate PR even if there is still some dependency. Code looks fine

**Comment by weizhang05** [comment]
Please separate AddGroupCommand and AddHouseCommand into 2 separate PR, 1 PR should be 1 thing and 1 thing only

**Review by weizhang05 — APPROVED** [review]
Implementation looks alright and fixes are done. PR accepted.

**Comment by shanseet** [comment]
Fixes #28

**Pull request merged**
